name: E2E Android

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message , '[skip ci]')"
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: gradle

      - name: install
        run: |
          yarn install --frozen-lockfile --non-interactive

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          emulator-build: 7425822
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          emulator-build: 7425822
          disable-animations: true
          script: yarn e2e:android-ci
